name: 'Unit Tests'
description: Action to run the full suite of unit tests

runs:
  using: composite
  steps:

    - name: Set up Python 3.10
      uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435
      with:
        python-version: "3.10"

    - name: Install dependencies
      shell: bash
      run: |
        pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-ansi

    - name: Test with pytest
      shell: bash
      run: |
        make unit-test
