name: Test, Build, and Publish to Stage Environment

on:
  push:
    branches:
      - main

jobs:
  run-code-lint:
    name: Code Lint 🧹
    runs-on: default
    steps:
      - uses: actions/checkout@v5
        name: Checkout Repo
      - uses: ./.github/actions/code-lint
        name: Code Lint

  run-unit-tests:
    name: Unit Testing 🧪
    runs-on: default
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Get GH app token
        id: gh-app-token
        uses: cloudbeds/composite-actions/gh-app-token@v2
        with:
          # replace <argocd-replace-with-your-repo> with the name of the argocd-repo that deploys your app
          repositories: >-
            ["<argocd-replace-with-your-repo>"]
          # replace <placeholders with your project/squad GH app details>
          app_name: <github-app-name>

      - uses: actions/checkout@v5
        name: Checkout Repo
      - uses: ./.github/actions/unit-tests
        name: Run Unit Tests
        env:
          GITHUB_ACCESS_TOKEN: ${{ steps.gh-app-token.outputs.github-token }}

  build-push:
    if: 0 # remove this line to enable this job
    name: Build and push image 🧱
    needs:
     - "run-unit-tests"
     - "run-code-lint"
    uses: ./.github/workflows/docker-build.yaml
    secrets: inherit
    with:
      push: true

  update-deployment:
    if: 0 # remove this line to enable this job
    name: Triggers action to update ArgoCD application deployment manifest with new image tag
    needs: build-push
    runs-on: x1-core
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Get GH app token
        id: gh-app-token
        uses: cloudbeds/composite-actions/gh-app-token@v2
        with:
          # replace <argocd-replace-with-your-repo> with the name of the argocd-repo that deploys your app
          repositories: >-
            ["<argocd-replace-with-your-repo>"]
          # replace <placeholders with your project/squad GH app details>
          app_name: <github-app-name>

      - name: Update application on stage cluster
        uses: cloudbeds/trigger-workflow-and-wait@v1.6.5
        with:
          owner: cloudbeds
          repo: argocd-${REPLACE_ME_WITH_YOUR_ARGO}
          github_token: ${{ steps.gh-app-token.outputs.github-token }}
          workflow_file_name: update-application.yaml
          client_payload: |
            {
              "cluster": "stage-ga", 
              "app_name": "${{ github.event.repository.name }}", 
              "image_tag": "${{ github.sha }}" 
            }
