name: Re-tag images and Push

on:
  push:
    tags:
      - 'v*'

jobs:

  re-tag:
    if: 0 # remove this line to enable this job
    name: Re-tag images
    runs-on: x1-core
    permissions:
      id-token: write
      contents: read
    steps:
      # Application Image
      - name: Re-tag application image
        uses: cloudbeds/composite-actions/docker/crane-re-tag/aws-ecr@v2
        with:
          image_name: ${{ github.event.repository.name }}
          src_tag: ${{ github.sha }}
          dst_tag: ${{ github.ref_name }}

  update-deployment:
    if: 0 # remove this line to enable this job
    name: Triggers action to update ArgoCD application deployment manifest with new image tag
    needs: re-tag
    runs-on: x1-core
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Update application on production cluster
        uses: cloudbeds/composite-actions/argocd/trigger-update-app@v2
        with:
          repo: cloudbeds/argocd-${REPLACE_ME_WITH_YOUR_ARGO}
          app-name: ${{ github.event.repository.name }}
          cluster: prod-ga
          image-tag: ${{ github.ref_name }}
